#!/bin/sh
#
# default services to run on login to X
#

. "${MY_PROFILE_PATH:-$HOME/.sh}/lib"
assert_sh_services_environment

if [ "$1" = "start" ]; then
    gnome-volume-control-applet &

    # Usually I run tmux on all systems but my work station
    #
    if ! uname -n | grep -i 'workstation' >/dev/null; then
        termargs="-e mytmux"
    fi

    ~/sw/sh.local/myterm $termargs &

    make_profile_link mutt/account
    make_profile_link mutt/aliases

    # only run these by default, if not using mobile Internet
    #
    if [ "`echo_this_profile MY_NETWORK_PROFILE`" != "mobile" ]; then
        make_profile_link gnubiffrc && gnubiff -n --systemtray &
        dropbox start -i &
    fi

elif [ "$1" = "stop" ]; then
    dropbox stop

    pkill gnubiff
    rm_profile_link gnubiffrc 

    rm_profile_link mutt/aliases
    rm_profile_link mutt/account

    pkill gnome-volume-control-applet

    # tmux?
fi
