#!/bin/sh

. "${MY_PROFILE_PATH:-$HOME/.sh}/lib"
assert_sh_services_environment

if [ "$1" = "start" ]; then
    pidgin -n &
elif [ "$1" = "stop" ]; then
    ~/sw/sh/xkillbyname "Buddy List" || pkill pidgin
fi
