#!/bin/sh

. "$MY_PROFILE_PATH/services.d/lib"

if [ "$1" = "start" ]; then
    ln -sf ~/.mutt/accounts.d/gmail ~/.mutt/account
    pidgin -n &
elif [ "$1" = "stop" ]; then
    rm_profile_link mutt/account
    ~/sw/sh/xkillbyname "Buddy List" || pkill pidgin
fi
