#!/bin/sh

. "${MY_PROFILE_PATH:-$HOME/.sh}/services.d/lib"
assert_sh_services_environment

if [ "$1" = "start" ]; then
    ln -sf ~/.mutt/accounts.d/work ~/.mutt/account

    # my workstation should run pidgin off my netbook
    if [ "`uname -n`" = "terry-Precision-WorkStation-T3400" ]; then
        ssh -X -f alice pidgin -n
    fi

elif [ "$1" = "stop" ]; then
    rm_profile_link mutt/account
fi
