#!/bin/sh

usage() {
  echo "usage:"
  echo "  $0 [options] {subject} -> open editor and post to Blogger /w note"
  echo "                            on Facebook"
  echo "  $0 -> not supported yet"
  echo
  echo "options: "
  echo "  -h                     display this usage message"
  echo "  -l 'tags, list'        apply labels to this post"
  exit
}

while getopts "hl:" opt; do
    case $opt in
        h)
            usage
            ;;
        l)
            LABELS="--tags '$OPTARG'"
            ;;
        \?)
            echo "Invalid option: -$OPTARG"
            ;;
    esac
done
shift `expr $OPTIND - 1`

if [ "$#" -eq 0 ]; then
    usage
fi


BLOGITDIR="/tmp/blogit/"
SUBJECT="$1"
FILE="${BLOGITDIR}${SUBJECT}.html"
mkdir -p "${BLOGITDIR}" 2>&1 >/dev/null
"$EDITOR" "$FILE"
if [ -e "$FILE" ]; then
    echo "Posting to blogger"
    # *groan* google blogger uses stderr
    note=$(google blogger post --title "$SUBJECT" $LABELS --src "$FILE"  2>&1 | sed -e 's/Post created: //')

    echo "Linking on Facebook"
    fbcmd feednote "Blogger post: ${SUBJECT}" "I've posted a new journal entry <a href=\"$note\">here</a>"

    echo "Moving blogit file to ${FILE}.backup.$$"
    mv "$FILE" "$FILE".backup$$
fi
