#!/bin/sh
#
# create a new script, with the shebang! pre-inserted.
#
# params:
#  $1   = interp
#  $2   = filename
#
if [ -z "$1" ]; then
    echo "Usage: $0 iterpname scriptname"
    return 0
fi
printf "#!/usr/bin/env $1\n\n" >> "$2" && chmod +x "$2"

