#!/bin/sh

if [ -n "$TMUX" ]; then
    # for some reason if I redir this commands stdout to /dev/null or any other
    # file on andrea, I get a long blocking event...
    #
    tmux set-window-option automatic-rename
    tmux rename-window notes
fi

my_notes_dir="${HOME}/n"
my_dsock="${TMPDIR:-/tmp}/notes.sock"
if [ -S "$my_dsock" ]; then
    dtach -a "$my_dsock"
else

    if ! cd "$my_notes_dir"; then
        echo "$0: failed to cd to notes dir, exiting"
        exit
    fi

    dtach -c "$my_dsock" vim -c 'normal zM' "${my_notes_dir}/ScratchNotes.viki"
fi

if [ -n "$TMUX" ]; then
    # oddly if I have two windows attached (in same session; idk about diff'
    # sessions) only one will be renamed when exiting vim :-/
    #
    tmux set-window-option automatic-rename
fi

