#!/usr/bin/env /bin/sh
#
# Rotate first conected screen, specified screens, or all connected screens.
#

rotate_list=""

get_displays() {
    xrandr -q | grep ' connected ' | cut -f 1 -d ' '
}
get_orientation() {
    xrandr -q | grep "$1" | cut -d ' ' -f 4 | sed -e 's/(//'
}

if [ "$1" = "--all" ]; then
    rotate_list=$(get_displays)
elif [ $# -eq 0 ]; then
    rotate_list=$(get_displays | head -n 1)
elif [ $# -gt 0 ]; then
    rotate_list="$*"
fi

# echo 'rotate_list: ' $rotate_list

for display in $rotate_list; do

    case $(get_orientation $display) in
        right|left)
            orientation=normal
            tablet=none
            ;;
        normal)
            orientation=right
            tablet=cw
            ;;
        *)
            orientation=IGNORE
            ;;
    esac

    echo "output: $display orientation: $orientation tablet: $tablet"

    xrandr --output "$display" --rotate "$orientation"

    pen=$(xsetwacom --list devices 2> /dev/null  | cut -f 1 -d ' ')
    [ -n "$pen" ] && xsetwacom --set "$pen" Rotate "$tablet"
done

