#!/bin/sh
# simple script to setup a port forward via the Android Debuging Bridge and connect via VNC
#

echo "Connect your phone via USB cable and start the server on your phone."

~/sw/src/android-sdk-linux_x86/platform-tools/adb forward tcp:5901 tcp:5901 && \
	exec vinagre localhost:5901

echo 'Failure.....bollocks!'
