#!/bin/sh
#
# This should be called from ~/.sh/xsession after setting up the universals.
#
#

#
# Startup programs and services.
#
# (
#     sleep 1
# 
#     # Freaking Basic Panel.
#     # -> Set TZ to desired clock setting.
#     # Use local profile if present.
#     #
#     env TZ="America/New_York" fbpanel -p $(
#         if [ -f "$HOME/.config/fbpanel/local" ]; then
#             echo local
#         else
#             echo default
#         fi
#     )&
# )

xscreensaver -no-splash&

if in_path -b compton; then
    compton -b
elif in_path -b xcompmgr; then
    xcompmgr -cfF &
else
    echo "$0: No supported compositor found."
fi

# if blueman is present, then I probably want to run the applet.
#
if in_path -b blueman-applet; then
    blueman-applet &
fi



# Start the big kahuna unless we were run from my xmonad-session-rc script.
#
[ "$XMONAD_SESSION_RC" = "true" ] || exec xmonad

