#!/bin/sh
#
# Simple daemon for watching the systems power state and running scripts accordingly
#
# Run it like: power-monitord [secs]
#
# Write a power profile as a ${MY_PROFILE_PATH:-$HOME/.sh}/power.d/{network
# profile name}.{hostname} shell script. It will be called with the power
# state: adapter, battery, or unknown. Your script should be safe to call multiple times.
#

. "${HOME}/.sh/lib"

shutdown_pmd() {
    # TODO: figure out how to shutdown the thing.
    #       we should probably do `set_power_profile shutdown` or something.
}


trap shutdown_pmd 0 INT TERM 

while true; do
    set_power_profile `get_power_state`

    # default wait of 7min between ticks should be OK
    sleep "${1:-420}"
done
