#!/bin/sh
#
# Script to configure services/apps during rc.xinit.
# It uses the current network to determine which "Profile" to load
#
# usage: services {start | stop} [profile]
#
# if profile is supplied, network determination is ommitted. This is for a use
# case like 'services stop work && services start', when changing networks.
#

MY_PROFILE_PATH="${HOME}/.sh"; export MY_PROFILE_PATH

# include some utility functions
#
. "$MY_PROFILE_PATH/services.d/lib"


if [ -n "$2" ]; then
    MY_NETWORK_PROFILE="$2"
else
    case `echo_network_connection` in
        "Auto BSDNet") # home
            NETWORK_NAME="BSDNet"
            ;;
        "Auto wegnet") # work
            NETWORK_NAME="wegnet"
            ;;
        "Auto SpideyMobile") # mobile (phone wifi)
            NETWORK_NAME="mobile"
            ;;
        "Auto usb*") # mobile (currently phone via tether)
            NETWORK_NAME="mobile"
            ;;
        "Auto eth0") # wired, check if wired or home
            if ifconfig eth0 | grep "inet addr:" | grep -E "172\.1[67]\..+\..+" >/dev/null; then
                NETWORK_NAME="engineering"
            else
                NETWORK_NAME="update $0 for this wired network!"
            fi
            ;;
        *)
            NETWORK_NAME="unknown"
            ;;
    esac

    MY_NETWORK_PROFILE="`echo_network_profile $NETWORK_NAME`"
fi

export MY_PROFILE_PATH NETWORK_NAME MY_NETWORK_PROFILE


services_d default "$1"
services_d "$MY_NETWORK_PROFILE" "$1"

