#!/bin/sh

# My personal X-Session initialization file.
#
#


#
# Force parsing of our current X resources file
#
xrdb -quiet ~/.Xresources


#
# launch a D-Bus channel for this session
#
which dbus-launch >/dev/null && if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi

# configure startup services based on network
#
# this assumes nmcli and Network Manager (common for Linux) which means we may
# NOT have a network connection setup until sometime after login. So run this
# as an external script in the background.
#
~/.sh/services start 

# configure monitors; this depends on ~/.sh/services having finished
#
~/.sh/monitors 



#
# Fancy shadows and things
#
xcompmgr -cfF &

# Freaking Basic Panel
#
fbpanel &

# Start the big kahuna
#
exec \
  env PATH="${HOME}/sw/sh.local:${HOME}/sw/sh:${HOME}/sw/bin:${HOME}/sw/sbin:$PATH" \
  xmonad

# clean up
#
echo "X-Session terminated"
