#!/bin/sh

# My personal X-Session initialization file.
#
#


#
# Force parsing of our current X resources file
#
xrdb -quiet ~/.Xresources


#
# launch a D-Bus channel for this session
#
which dbus-launch >/dev/null && if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi


# configure startup services based on network
#
# this assumes nmcli and Network Manager (common for Linux) which means we may
# NOT have a network connection setup until sometime after login. So run this
# as an external script in the background.
#
~/.sh/services start &



#
# Fancy shadows and things
#
xcompmgr -cfF &

# start the big kahuna
fbpanel &
exec xmonad

# clean up
echo "X-Session terminated"
