#!/bin/sh
#
# My personal X-Session initialization file.
#
#


#
# Force parsing of our current X resources file.
# -> This should only be needed on old Xorg versions.
# -> Modern Xorg versions should automate this in XSession.
#
xrdb -quiet ~/.Xresources

# Fix the wonky mouse cursor X -> arrow.
# -> This should only be needed on newer Xorg versions.
#
xsetroot -cursor_name left_ptr

#
# Launch a D-Bus channel for this session if missing.
# -> Modern Xorg versions should automate this in XSession.
#
which dbus-launch >/dev/null && if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi

# configure startup services based on network
#
# this assumes nmcli and Network Manager (common for Linux) which means we may
# NOT have a network connection setup until sometime after login. So run this
# as an external script in the background.
#
# sh-services start 

# configure monitors; this depends on ~/.sh/services having finished
#
# ~/.sh/monitors 

    dropbox start -i &

# if running on a laptop, try to disable the touch pad while typing
#
if laptop-detect; then
    # [ ! -f "${HOME}/tmp/syndaemon.pid" ] &&
    syndaemon -d -tK -i 0.5 #-p "${HOME}/tmp/syndaemon.pid"
    # TODO: a way of trapping logout events for cleanup
fi

# run jwz's screen saver and locking program
#
xscreensaver -no-splash &


#
# Fancy shadows and things
#
xcompmgr -cfF &

# Freaking Basic Panel
#
env TZ="America/New_York" fbpanel &

# if blueman is present, then I probably want to run the applet.
if type blueman-applet; then
    blueman-applet&
fi

pidgin&

# Start XTerm/tmux with a delay. Other wise some window managers may get the
# layout wrong in relation to fbpanel.
#
# (sleep 3; if type tmux; then xterm -e ~/sw/sh/mytmux & 
 # else xterm & fi)
 (sleep 3; google-chrome&)

# Start the big kahuna
#
exec xmonad

# clean up
#
echo "X-Session terminated"
