#!/bin/sh
#
# My personal X-Session initialization file.
#
#

#
# Utility functions.
#
. ~/.sh/lib

#
# If these are not in PATH, force them.
#
ensure_path -p "/usr/local/bin"
ensure_path -p "/usr/local/sbin"
ensure_path -p "$HOME/sw/bin"
ensure_path -p "$HOME/sw/sbin"
ensure_path -p "$HOME/sw/sh"
ensure_path -p "$HOME/sw/sh.local"

#
# Force parsing of our current X resources file.
# -> This should only be needed on old Xorg versions.
# -> Modern Xorg versions should automate this in XSession.
#
xrdb -quiet -merge ~/.Xresources

# Fix the wonky mouse cursor X -> arrow.
# -> This should only be needed on newer Xorg versions.
#
xsetroot -cursor_name left_ptr

# Load custom X key maps.
#
[ -f ~/.Xmodmap ] && xmodmap ~/.Xmodmap
[ -f "${HOME}/.sh/xmodmap.d/$(hostname -s)" ] && xmodmap ~/.sh/xmodmap.d/$(hostname -s)

#
# Launch a D-Bus channel for this session if missing.
# -> Modern systems automate this as part of Xorg's XSession.
# -> Or in through the init system.
#
if in_path -e dbus-launch && [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval `dbus-launch --sh-syntax --exit-with-session`
fi


# I want gnome-keyring to unlock when I login to my session.
#
# Requires PAM suitably configured and keyring password to match user account.
#
if in_path -e gnome-keyring-daemon; then
    eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
    export SSH_AUTH_SOCK
fi

# if running on a laptop, try to disable the touch pad while typing
#
if in_path -e laptop-detect && laptop-detect && in_path -e syndaemon; then
    # [ ! -f "${HOME}/tmp/syndaemon.pid" ] &&
    syndaemon -d -tK -i 0.5 #-p "${HOME}/tmp/syndaemon.pid"
    # TODO: a way of trapping logout events for cleanup
fi


# Start the big kahuna
#
gst-play-1.0 --no-interactive --quiet /usr/local/etc/startup.ogg &
[ -x ~/.sh/xsession.d/local ] && . ~/.sh/xsession.d/local
gst-play-1.0 --no-interactive --quiet /usr/local/etc/shutdown.ogg &

# clean up
#
echo "X-Session terminated"

