#!/bin/sh
#
# My personal X-Session initialization file.
#
#

#
# Utility functions.
#
. ~/.sh/lib

#
# If these are not in PATH, force them.
#
ensure_path -p "/usr/local/bin"
ensure_path -p "/usr/local/sbin"
ensure_path -p "$HOME/sw/bin"
ensure_path -p "$HOME/sw/sbin"
ensure_path -p "$HOME/sw/sh"
ensure_path -p "$HOME/sw/sh.local"

#
# Force parsing of our current X resources file.
# -> This should only be needed on old Xorg versions.
# -> Modern Xorg versions should automate this in XSession.
#
xrdb -quiet ~/.Xresources

# Fix the wonky mouse cursor X -> arrow.
# -> This should only be needed on newer Xorg versions.
#
xsetroot -cursor_name left_ptr

#
# Launch a D-Bus channel for this session if missing.
# -> Modern Xorg versions should automate this in XSession.
# -> This doesn't seem to be working anymore (Debian/2012-12-17).
#
# which dbus-launch >/dev/null && if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    # eval `dbus-launch --sh-syntax --exit-with-session`
# fi

# if running on a laptop, try to disable the touch pad while typing
#
if in_path -b laptop-detect && laptop-detect; then
    # [ ! -f "${HOME}/tmp/syndaemon.pid" ] &&
    syndaemon -d -tK -i 0.5 #-p "${HOME}/tmp/syndaemon.pid"
    # TODO: a way of trapping logout events for cleanup
fi


# Start the big kahuna
#
[ -x ~/.sh/xsession.d/local ] && . ~/.sh/xsession.d/local

# clean up
#
echo "X-Session terminated"

