#!/bin/sh

if [ $# -eq 1 ]; then
    # only the onboard monitor; nothing to do (usually).
	exit 0
fi

for monitor; do

    case $monitor in
        LVDS1) # onboard monitor.
            xrandr --output $monitor --auto 
            ;;
        VGA1) # external monitor.
            xrandr --output $monitor --auto --primary --left-of LVDS1
            xrandr --output LVDS1 --pos 1600x432
            ;;
        *)
            echo "unknown monitor: $monitor"
            ;;
    esac
done

